### ISSUE TITLE
UI/UX Rubric

### ISSUE THREAD

**Issue by Card0154** [Web-Dev-6-Mega/mega-app#15]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Design** | No design considerations were made | Design is the result of minimal effort | Content is well laid out | Content is pixel perfect and the design communicates our message. |
| **Wireframe** | Incomplete | Wireframes are low fidelity and no design consideration was made | Wireframes are acceptable and some design consideration was made | Wireframes are high fidelity, following industry standards and guidelines |
| **Prototype** | Incomplete | Prototype is low fidelity and no design consideration was made | Prototype is acceptable and some design consideration was made | Prototype is high fidelity, following industry standards and guidelines |
| **Peer Evaluation** | Only negative feedback | Mostly negative feedback | Mostly positive feedback | Only positive feedback |
| **Presentation** | Didn't show up / didn't present | One group member is missing / unprepared | Everyone is comfortable with presentation and content | Everyone is an expert in app-related content / Presentation was professional |

**Comment by cstewartottawa** [comment]
Design: 3 - Solid overall design, clean, simple.
Wireframe: 3 - Completed on time and were a good starting point.
Prototype: 2 - Some un-clickable buttons, good prototype but room for improvement.
Peer Evaluation: 3 - Usability was fairly intuitive, not a complicated interface.
Presentation: 3 - Everyone was comfortable with presentation and content.
