### ISSUE TITLE
Sprint 2 Review

### ISSUE THREAD

**Issue by Card0154** [Web-Dev-6-Mega/mega-app#16]
- [x] Initial Preparation
- [x] Research
- [x] Brainstorming
- [x] Logo Design

## Workload
Logo design is still in progress due to indecision over startup app name. Will create a new issue in Sprint 3 in order to track progress. The rest of the work was completed before the class ended, giving us ample time to prepare for this week.

## Team Dynamics
The team communicated effectively and used our time well. Everyone's opinions and ideas were considered, and criticism was kept constructive.

@thomasjbradley

**Comment by thomasjbradley** [comment]
This is very incomplete—each person on the team should have commented with their own personal reflections from the Sprint.

---

The Sprint 2 Issues could be more detailed—some of them are great—but others lacking.
The biggest thing missing is that the Project board and Issues aren’t up to date. Many of the Issues are still open. Looking at the Issues tab it seems like nothing has been completed on this project.
